name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'chmod'
        run: bash ./code/chmod.sh
      - name: 'tranfer'
        run: bash ./code/tranfer.sh
      - name: download
        run: |
          git config --local user.email "123354572+CollapseEdge@users.noreply.github.com"
          git config --local user.name "CollapseEdge"
          ./yt-dlp --config-location ./code/config.txt
          ./code/upload.sh
          git add .
          git commit -m "download youtube video"
          git push

